### ISSUE TITLE
Tx builder example for pool minting

### ISSUE THREAD

**Issue by mpizenberg** [elm-cardano/elm-cardano#76]
From Pi’s description in TxPipe discord https://discord.com/channels/946071061567529010/1218161517032116285/1309200876568838266

I only half read the above conversation, but here's an interesting example of a transaction building wrinkle we have santicarmu:
- for minting a pool, the "Pool ID" appears in the datum
- This ID is a hash of the first TxRef in the input
- TxRefs are sorted lexographically
- This means that we need to know what inputs are used when we build the output datum, but the output datum might impact the fee / minUTxO which might impact UTxO selection

We've worked around it in other tx builders by just always including the smallest UTxO in the users wallet 😅  but that's another example where that multipass approach might be helpful, if you want to wargame whether your approach supports it

**Comment by keyan-m** [comment]
What would be the downside of simply passing the TxRef via the redeemer?

**Comment by mpizenberg** [comment]
Ok, maybe not that useful ^^
